Repository ManageIQ/manageiq-providers-red_hat_virtualization, pull requests merged in 2024-02, with the labels that each got.

#40 Drop require_nested and include_concern
  app/models/manageiq/providers/redhat/infra_manager.rb
  app/models/manageiq/providers/redhat/infra_manager/event_catcher.rb
  app/models/manageiq/providers/redhat/infra_manager/metrics_collector_worker.rb
  app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb
  app/models/manageiq/providers/redhat/infra_manager/provision_via_iso.rb
  app/models/manageiq/providers/redhat/infra_manager/provision_via_pxe.rb
  app/models/manageiq/providers/redhat/infra_manager/refresh_worker.rb
  app/models/manageiq/providers/redhat/infra_manager/scanning.rb
  app/models/manageiq/providers/redhat/infra_manager/template.rb
  app/models/manageiq/providers/redhat/infra_manager/vm.rb
  app/models/manageiq/providers/redhat/infra_manager/vm_or_template_shared.rb
  app/models/manageiq/providers/redhat/inventory.rb
  app/models/manageiq/providers/redhat/inventory/collector.rb
  app/models/manageiq/providers/redhat/inventory/parser.rb
  app/models/manageiq/providers/redhat/inventory/persister.rb
  app/models/manageiq/providers/redhat/network_manager.rb
  app/models/manageiq/providers/redhat/network_manager/cloud_network.rb
  app/models/manageiq/providers/redhat/network_manager/refresh_worker.rb
Labels: rails7, technical debt

#41 Set minimum version to support rails 7
  manageiq-providers-red_hat_virtualization.gemspec
Labels: rails7

#42 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#44 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1

#43 drop unsupported_reason_add
  app/models/manageiq/providers/redhat/infra_manager/host.rb
  app/models/manageiq/providers/redhat/infra_manager/template.rb
  app/models/manageiq/providers/redhat/infra_manager/vm.rb
Labels: technical debt, radjabov/yes?
